# PersistentVolume for MongoDB
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-local-pv
spec:
  capacity:
    storage: {{.Values.mongo.mongo_local_pv.storage}}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongo
  local:
    path: /opt/fiware/mongo
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - {{.Values.mongo.mongo_local_pv.host}}
