apiVersion: v1
kind: Service
metadata:
  name: mongo-config-svc
  labels:
    app: mongo-config
spec:
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
    name: mongo-main
  clusterIP: None
  selector:
    app: mongo-config
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-config
  labels:
    app: mongo-config
spec:
  serviceName: "mongo-config-svc"
  selector:
    matchLabels:
      app: mongo-config
  replicas: 3
  template:
    metadata:
      labels:
        app: mongo-config
      name: mongo-config
    spec:
      containers:
      - name: mongo-config
        image: mongo:3.6.9
        command:
        - "mongod"
        - "--keyFile"
        - "/etc/secrets/mongodb-keyfile"
        - "--configsvr"
        - "--replSet"
        - "crs"
        - "--port"
        - "27017"
        - "--dbpath"
        - "/data/db"
        - "--bind_ip"
        - "0.0.0.0"
        ports:
        - containerPort: 27017
          name: mongo-main
        volumeMounts:
          - mountPath: /etc/secrets
            name: secrets
          - mountPath: /data/db
            name: mongo-config-pv
      volumes:
        - name: secrets
          secret:
            secretName: mongodb-key
            defaultMode: 256
  volumeClaimTemplates:
  - metadata:
      name: mongo-config-pv
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "mongo-config"
      resources:
        requests:
          storage: 10Gi