apiVersion: v1
kind: Service
metadata:
  name: mongo-router-svc
  labels:
    app: mongo-router
spec:
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
    name: mongo-main
  clusterIP: None
  selector:
    app: mongo-router
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-router
  labels:
    app: mongo-router
spec:
  serviceName: "mongo-router-svc"
  selector:
    matchLabels:
      app: mongo-router
  replicas: 2
  template:
    metadata:
      labels:
        app: mongo-router
      name: mongo-router
    spec:
      containers:
      - name: mongo-router
        image: mongo:3.6.9
        command:
        - "mongos"
        - "--port"
        - "27017"
        - "--bind_ip"
        - "0.0.0.0"
        - "--configdb"
        - "crs/mongo-config-0.mongo-config-svc.mongo.svc.cluster.local:27017,mongo-config-1.mongo-config-svc.mongo.svc.cluster.local:27017,mongo-config-2.mongo-config-svc.mongo.svc.cluster.local:27017"
        - "--keyFile"
        - "/etc/secrets/mongodb-keyfile"
        ports:
        - containerPort: 27017
          name: mongo-main
        volumeMounts:
          - mountPath: /etc/secrets
            name: secrets
      volumes:
        - name: secrets
          secret:
            secretName: mongodb-key
            defaultMode: 256