apiVersion: v1
kind: Service
metadata:
  name: namenode
  labels:
    app: namenode
spec:
  ports:
  - port: 9870
    name: webhdfs
  - port: 9000
    name: defaultfs
  clusterIP: None
  selector:
     app: namenode
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-namenode
spec:
  selector:
    matchLabels:
      app: namenode # has to match .spec.template.metadata.labels
  serviceName: "namenode"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: namenode # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: namenode
        image: bxjulia/namenode-3.1.0:latest
        ports:
        - containerPort: 9870
          name: webhdfs
        - containerPort: 9000
          name: defaultfs
        volumeMounts:
        - name: namenode-pv-1
          mountPath: /hdfs/volume1/name
  volumeClaimTemplates:
  - metadata:
      name: namenode-pv-1
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "namenode"
      resources:
        requests:
          storage: 20Gi
