apiVersion: v1
kind: PersistentVolume
metadata:
  name: namenode-local-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: namenode
  local:
    path: /opt/hadoop/hdfs/name
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - i101v181
