apiVersion: v1
kind: PersistentVolume
metadata:
  name: namenode-pv-1
  labels:
    type: namenode
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: namenode
  hostPath:
    path: "/hdfs/volume1/name"
