apiVersion: apps/v1
kind: Deployment
metadata:
  name: orion
spec:
  selector:
    matchLabels:
      run: orion
  replicas: 1
  template:
    metadata:
      labels:
        run: orion
    spec:
      containers:
      - name: orion
        image: {{.Values.orion.image}}
        args:
        - -dbhost
        - {{.Values.orion.dbhost}}
        ports:
        - containerPort: 1026
