apiVersion: v1
kind: Service
metadata:
  name: orion
  labels:
    run: orion
spec:
  ports:
  - port: 1026
    targetPort: 1026
  selector:
    run: orion
  type: ClusterIP

{{ if .Value.mongo.external }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-external
  labels:
    app: mongo
spec:
  ports:
  - port: 1016
    nodePort: 31026
  type: LoadBalancer
  selector:
     app: mysql
{{- end}}
