apiVersion: v1
kind: Service
metadata:
  name: comet
  namespace: {{.Values.fiware.namespace}}
  labels:
    run: comet
spec:
  ports:
  - name: "8666"
    port: 8666
    targetPort: 8666
  selector:
    run: comet
  type: ClusterIP
