apiVersion: v1
kind: Service
metadata:
  name: cygnus
  namespace: {{.Values.fiware.namespace}}
  labels:
    run: cygnus
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  - name: "5050"
    port: 5050
    targetPort: 5050
  selector:
    run: cygnus
