apiVersion: apps/v1
kind: Deployment
metadata:
  name: keyrock
  namespace: {{.Values.fiware.namespace}}
spec:
  selector:
    matchLabels:
      run: keyrock
  replicas: 1
  template:
    metadata:
      labels:
        run: keyrock
    spec:
      containers:
      - name: keyrock
        image: {{.Values.keyrock.image}}
        env:
        - name: DATABASE_HOST
          value: "mysql"
        - name: IDM_PDP_LEVEL
          value: "basic"
        - name: IDM_AUTHZFORCE_ENABLED
          value: "false"
        - name: IDM_PORT
          value: "5000"
        - name: IDM_HOST
          value: "{{.Values.keyrock.idm_host}}"
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /opt/fiware-idm/config.js
          name: keyrock-config
          subPath: config.js
        - mountPath: /opt/fiware-idm/lib/authzforce_templates/policy.ejs
          name: keyrock-config
          subPath: policy.ejs
      restartPolicy: Always
      volumes:
      - name: keyrock-config
        configMap:
          name: keyrock-config
