apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: {{.Values.fiware.namespace}}
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    name: fiware-mysql
  clusterIP: None
  selector:
     app: mysql
