apiVersion: v1
kind: Service
metadata:
  name: orion
  namespace: {{.Values.fiware.namespace}}
  labels:
    run: orion
spec:
  ports:
  - port: 1026
    targetPort: 1026
  selector:
    run: orion
  type: ClusterIP
