apiVersion: v1
kind: Service
metadata:
  name: pep-idas-sensor
  namespace: {{.Values.fiware.namespace}}
  labels:
    run: pep-idas-sensor
spec:
  ports:
  - port: 7896
    targetPort: 7896
    nodePort: {{.Values.pep.idas_sensor.nodePort}}
  selector:
    run: pep-idas-sensor
  type: LoadBalancer
