apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{.Values.fiware.namespace}}
  labels:
    run: postgres
spec:
  ports:
  - port: 5432
    name: postgres
  selector:
     run: postgres
  type: ClusterIP
