version: '2.1'
services:
    mongodb:
        restart: on-failure
        image: mongo:3.4
        hostname: mongodb
        container_name: mongodb
        command: --smallfiles
        ports:
            - "27017:27017"

    orion:
        restart: on-failure
        image: fiware/orion:1.14.0
        hostname: orion
        container_name: orion
        command: -dbhost mongodb
        ports:
            - "1026:1026"

    cygnus:
        restart: on-failure
        image: januschm/cygnus-ngsi
        hostname: cygnus
        container_name: cygnus
        links:
            - mongodb:iot-mongo
        volumes:
            - ./cygnus_config/agent.conf:/opt/apache-flume/conf/agent.conf:ro

    idas:
        restart: on-failure
        image: fiware/iotagent-ul:1.6.0
        hostname: idas
        container_name: idas
        links:
            - mongodb:mongo
        ports:
            - "4041:4041"
            - "7896:7896"
    
    nodered:
        restart: on-failure
        image: nodered/node-red-docker
        hostname: nodered
        container_name: nodered
        user: root
        volumes:
            - ./nodered_data:/data:rw
        ports:
            - "31880:1880"