apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-router-svc
  labels:
    app: {{ .Release.Name }}-router
spec:
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
    name: mongo-main
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-router
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-router
  labels:
    app: {{ .Release.Name }}-router
spec:
  serviceName: "{{ .Release.Name }}-router-svc"
  selector:
    matchLabels:
      app: {{ .Release.Name }}-router
  replicas: {{ .Values.router.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-router
      name: {{ .Release.Name }}-router
    spec:
      containers:
      - name: {{ .Release.Name }}-router
        image: mongo:{{ .Values.mongoVersion }}
        command:
        - "mongos"
        - "--port"
        - "27017"
        - "--bind_ip"
        - "0.0.0.0"
        - "--configdb"
        {{- $rName := .Release.Name -}}
        {{- $namespace := .Release.Namespace -}}
        {{ $configDBs := cat "crs/" $rName "-config-0." $rName "-config-svc." $namespace ".svc.cluster.local:27017" }}
        {{- range $number := untilStep 1 (int .Values.config.replicas) 1 -}}
         {{$configDBs = cat $configDBs  "," $rName "-config-" $number "." $rName "-config-svc." $namespace ".svc.cluster.local:27017" }}
        {{- end }}
        - {{ $configDBs | replace " " "" | quote}}
        - "--keyFile"
        - "/etc/secrets/mongodb-keyfile"
        ports:
        - containerPort: 27017
          name: mongo-main
        volumeMounts:
          - mountPath: /etc/secrets
            name: secrets
      volumes:
        - name: secrets
          secret:
            secretName: mongodb-key
            defaultMode: 256
