apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-config-svc
  labels:
    app: {{ .Release.Name }}-config
spec:
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
    name: mongo-main
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-config
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}-config
spec:
  serviceName: "{{ .Release.Name }}-config-svc"
  selector:
    matchLabels:
      app: {{ .Release.Name }}-config
  replicas: {{ .Values.config.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-config
      name: {{ .Release.Name }}-config
    spec:
      containers:
      - name: {{ .Release.Name }}-config
        image: mongo:{{ .Values.mongoVersion }}
        command:
        - "mongod"
        - "--keyFile"
        - "/etc/secrets/mongodb-keyfile"
        - "--configsvr"
        - "--replSet"
        - "crs"
        - "--port"
        - "27017"
        - "--dbpath"
        - "/data/db"
        - "--bind_ip"
        - "0.0.0.0"
        ports:
        - containerPort: 27017
          name: mongo-main
        volumeMounts:
          - mountPath: /etc/secrets
            name: secrets
          - mountPath: /data/db
            name: {{ .Release.Name}}-config-pv
      volumes:
        - name: secrets
          secret:
            secretName: mongodb-key
            defaultMode: 256
  volumeClaimTemplates:
  - metadata:
      name: {{ .Release.Name }}-config-pv
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "{{ .Release.Name }}-config"
      resources:
        requests:
          storage: {{ .Values.config.size }}
