apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql # has to match .spec.template.metadata.labels
  serviceName: "mysql"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: mysql # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mysql
        image: mysql/mysql-server:{{.Values.mysql.version}}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysql.root_password | quote}}
        - name: MYSQL_ROOT_HOST
          value: "%"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-pv-1
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-pv-1
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Release.Namespace}}-mysql
      resources:
        requests:
          storage: {{.Values.mysql.storage}}
