apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - port: {{ .Values.keyrock.database.port }}
    name: fiware-mysql
  clusterIP: None
  selector:
     app: mysql
