apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
spec:
  selector:
    matchLabels:
      run: memcached
  replicas: 1
  template:
    metadata:
      labels:
        run: memcached
    spec:
      containers:
      - name: memcached
        image: memcached
        ports:
        - containerPort: 11211
        command: ['memcached', '-m', '2048m']
