apiVersion: v1
kind: Service
metadata:
  name: memcached
  labels:
    run: memcached
spec:
  ports:
  - port: {{ .Values.memcached.containerPort}}
    name: memcached
  selector:
     run: memcached
  type: ClusterIP
