apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: {{ .Release.Namespace }}-postgres
  accessModes:
  - {{.Values.postgres.pv.accessModes}}
  resources:
     requests:
       storage: {{.Values.postgres.pv.storage}}
