apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      run: postgres
  replicas: 1
  serviceName: "postgres"
  template:
    metadata:
      labels:
        run: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "wirepass"
        volumeMounts:
           - mountPath: /var/lib/postgresql/data
             name: postgres-volume
      volumes:
      - name: postgres-volume
        persistentVolumeClaim:
          claimName: postgres-pvc
