apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      run: postgres
  replicas: 1
  serviceName: "postgres"
  template:
    metadata:
      labels:
        run: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: {{ .Values.wirecloud.db.username | default "postgres" | quote }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.wirecloud.db.password | default "wirepass" | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.wirecloud.db.dbName | default "wirecloud" | quote}}
        volumeMounts:
           - mountPath: /var/lib/postgresql/data
             name: postgres-volume
        securityContext:
          runAsUser: 0
          fsGroup: 65534
      volumes:
      - name: postgres-volume
        persistentVolumeClaim:
          claimName: postgres-pvc
