apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: {{.Values.fiware.namespace}}
spec:
  accessModes:
  - {{.Values.postgres.postgres_pvc.accessModes}}
  resources:
     requests:
       storage: {{.Values.postgres.postgres_pvc.storage}}
