apiVersion: apps/v1
kind: Deployment
metadata:
  name: wirecloud
spec:
  selector:
    matchLabels:
      run: wirecloud
  replicas: 1
  template:
    metadata:
      labels:
        run: wirecloud
    spec:
      containers:
      - name: wirecloud
        image: {{.Values.wirecloud.image}}
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
          value: "true"
        - name: DB_NAME
          value: {{ .Values.wirecloud.db.dbName | default "wirecloud" | quote }}
        - name: DB_USERNAME
          value: {{ .Values.wirecloud.db.username | default "postgres" | quote }}
        - name: DB_HOST
          value: {{ .Values.wirecloud.db.host | default "postgres" | quote }}
        - name: DB_PASSWORD
          value: {{ .Values.wirecloud.db.password | default "wirepass" | quote }}
        - name: FORWARDED_ALLOW_IPS
          value: "*"
        - name: MEMCACHED_LOCATION
          value: "memcached:{{ .Values.memcached.containerPort}}"
        - name: FIWARE_IDM_SERVER
          value: {{ if .Values.keyrock.debug_local }}{{ cat "http://" .Values.keyrock.debug_local.ip ":" .Values.keyrock.debug_local.port | replace " " "" |quote }}{{else}}{{quote .Values.keyrock.idm_host}}{{end}}
        - name: SOCIAL_AUTH_FIWARE_KEY
          value: {{quote .Values.wirecloud.env.social_auth_fiware_key}}
        - name: SOCIAL_AUTH_FIWARE_SECRET
          value: {{quote .Values.wirecloud.env.social_auth_fiware_secret}}
        - name: FORCE_PORT
          value: {{quote .Values.wirecloud.nodePort}}
        - name: "ELASTICSEARCH2_URL"
          value: "http://elasticsearch:{{ .Values.elasticsearch.containerPort}}/"
        volumeMounts:
         - mountPath: /opt/wirecloud_instance/data
           name: wirecloud-pvc
           subPath: data
         - mountPath: /var/www/static
           name: wirecloud-pvc
           subPath: static
         - mountPath: /opt/wirecloud_instance/wirecloud_instance/settings.py
           name: wirecloud-config
           subPath: settings.py
      - name: nginx-wirecloud
        image: nginx
        ports:
        - containerPort: {{.Values.wirecloud.nodePort}}
        volumeMounts:
           - mountPath: /var/www/static
             name: wirecloud-pvc
             subPath: static
           - mountPath: /etc/nginx/nginx.conf
             name: nginx-wirecloud-config
             subPath: nginx.conf
             readOnly: true
      securityContext:
        runAsUser: 0
        fsGroup: 65534
      volumes:
      - name: wirecloud-pvc
        persistentVolumeClaim:
          claimName: wirecloud-pvc
      #- name: wirecloud-static
      #  persistentVolumeClaim:
      #    claimName: wirecloud-static-pvc
      - name: nginx-wirecloud-config
        configMap:
          name: nginx-wirecloud-config
      - name: wirecloud-config
        configMap:
          name: wirecloud-config
