apiVersion: v1
kind: PersistentVolume
metadata:
  name: datanode1-local-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: datanode1
  local:
    path: /opt/hadoop/hdfs/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - i101v181
