apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-shard2-local-pv1
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongo-shard2
  local:
    path: /opt/mongo/shard2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - i101v182