version: '2'
services:
    mongodb:
        restart: on-failure
        image: mongo:latest
        hostname: mongodb
        container_name: mongodb
        expose:
            - "27017"
        ports:
            - "27017:27017"
        command: --smallfiles

    orion:
        restart: on-failure
        image: fiware/orion:latest
        hostname: orion
        container_name: orion
        links:
            - mongodb
        expose:
            - "1026"
        ports:
            - "1026:1026"
        command: -dbhost mongodb

    cygnus:
        restart: on-failure
        image: telefonicaiot/fiware-cygnus
        hostname: cygnus
        container_name: cygnus
        links:
            - mongodb:iot-mongo
        expose:
            - "8081"
            - "5050"
        ports:
            - "8081:8081"
            - "5050:5050"
        volumes:
            - "./cygnus_config/agent.conf:/opt/apache-flume/conf/agent.conf:ro"

    comet:
        restart: on-failure
        image: fiware/sth-comet
        hostname: comet
        container_name: comet
        links:
            - mongodb
        expose:
            - "8666"
        ports:
            - "8666:8666"
        volumes: 
            - "./comet_config/config.js:/opt/sth/config.js:ro"

    idas:
        restart: on-failure
        image: fiware/iotagent-ul:latest
        hostname: idas
        container_name: idas
        links:
            - orion
            - mongodb:mongo
        expose:
            - "7896"
            - "4041"
        ports:
            - "7896:7896"
            - "4041:4041"

    nginx:
        restart: on-failure
        image: nginx:latest
        hostname: nginx
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx_config/certs/:/etc/nginx/certs/:ro
            - letsencrypt_www:/var/www/letsencrypt/
        volumes_from:
            - wirecloud
        links:
            - wirecloud:wirecloud

    certbot:
        image: certbot/certbot:latest
        hostname: certbot
        container_name: certbot
        volumes:
            - ./nginx_config/certs/:/etc/letsencrypt/
            - letsencrypt_www:/var/www/letsencrypt/

    postgres:
        restart: on-failure
        image: postgres:latest
        hostname: postgres
        container_name: postgres
        volumes_from:
            - data
        ports:
            - "5432:5432"

    data:
        restart: on-failure
        image: postgres:latest
        hostname: data
        container_name: data
        volumes:
            - /var/lib/postgresql
        command: /bin/true

    wirecloud:
        restart: on-failure
        image: fiware/wirecloud:latest-composable
        hostname: wirecloud
        container_name: wirecloud
        volumes:
            - ./wirecloud_config/graziotthemev2/:/opt/wirecloud_instance/graziotthemev2/:ro
            - ./wirecloud_config/settings.py:/opt/wirecloud_instance/wirecloud_instance/settings.py:ro
        links:
            - postgres:postgres

    ngsi-proxy:
        restart: on-failure
        image: januschm/ngsi-proxy:latest
        hostname: ngsi-proxy
        container_name: ngsi-proxy
        expose:
            - "3000"
        ports:
            - "3000:3000"

volumes:
    letsencrypt_www: ~
