version: '2.1'
services:
    mysql:
        restart: on-failure
        image: mysql/mysql-server:5.7.21
        hostname: mysql
        container_name: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=idm
            - MYSQL_ROOT_HOST=172.18.1.100
        volumes:
            - mysql_vol:/var/lib/mysql
        networks:
            - fiware
        ports:
            - "3306:3306"

    mongodb:
        restart: on-failure
        image: mongo:latest
        hostname: mongodb
        container_name: mongodb
        networks:
            - fiware
        ports:
            - "27017:27017"
        command: --smallfiles

    postgres:
        restart: on-failure
        image: postgres:latest
        hostname: postgres
        container_name: postgres
        volumes:
            - postgres_vol:/var/lib/postgresql
        networks:
            - fiware
        ports:
            - "5432:5432"

    authzforce:
        restart: on-failure
        image: fiware/authzforce-ce-server:latest-unstable
        hostname: authzforce
        container_name: authzforce
        volumes:
            - authzforce_vol:/opt/authzforce-ce-server/data
        networks:
            - fiware
        ports:
            - "8080:8080"
        expose:
            - "8080"

    keyrock:
        restart: on-failure
        image: fiware/idm:latest
        hostname: keyrock
        container_name: keyrock
        volumes:
            - ./keyrock_config/config.js:/opt/fiware-idm/config.js:ro
            - ./nginx_config/certs/:/opt/fiware-idm/certs/:ro
        networks:
            fiware:
                ipv4_address: 172.18.1.100
        environment:
            - DATABASE_HOST=mysql
        ports:
            - "5000:5000"
        links:
            - authzforce
        healthcheck:
            test: ["CMD-SHELL", "nc -z -v -w 30 mysql 3306"]
            interval: 10s
            timeout: 3s
            retries: 6

    orion:
        restart: on-failure
        image: fiware/orion:latest
        hostname: orion
        container_name: orion
        links:
            - mongodb
        networks:
            - fiware
        expose:
            - "1026"
        command: -dbhost mongodb

    cygnus:
        restart: on-failure
        image: telefonicaiot/fiware-cygnus
        hostname: cygnus
        container_name: cygnus
        links:
            - mongodb:iot-mongo
        volumes:
            - "./cygnus_config/agent.conf:/opt/apache-flume/conf/agent.conf:ro"
        networks:
            - fiware
        expose:
            - "8081"
            - "5050"

    comet:
        restart: on-failure
        image: fiware/sth-comet
        hostname: comet
        container_name: comet
        links:
            - mongodb
        volumes: 
            - "./comet_config/config.js:/opt/sth/config.js:ro"
        networks:
            - fiware
        expose:
            - "8666"

    idas:
        restart: on-failure
        image: fiware/iotagent-ul:latest
        hostname: idas
        container_name: idas
        links:
            - orion
            - mongodb:mongo
        networks:
            - fiware
        expose:
            - "7896"
            - "4041"

    nginx:
        restart: on-failure
        image: nginx:latest
        hostname: nginx
        container_name: nginx
        volumes:
            - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx_config/certs/:/etc/nginx/certs/:ro
            - letsencrypt_www:/var/www/letsencrypt/
        volumes_from:
            - wirecloud
        networks:
            - fiware
        ports:
            - "80:80"
            - "443:443"
            - "3000:3000"
        links:
            - wirecloud

    certbot:
        image: certbot/certbot:latest
        hostname: certbot
        container_name: certbot
        volumes:
            - ./nginx_config/certs/:/etc/letsencrypt/
            - letsencrypt_www:/var/www/letsencrypt/
        networks:
            - fiware

    wirecloud:
        restart: on-failure
        image: fiware/wirecloud:latest-composable
        hostname: wirecloud
        container_name: wirecloud
        volumes:
            - ./wirecloud_config/graziotthemev2/:/opt/wirecloud_instance/graziotthemev2/:ro
            - ./wirecloud_config/settings.py:/opt/wirecloud_instance/wirecloud_instance/settings.py:ro
            - ./wirecloud_config/urls.py:/opt/wirecloud_instance/wirecloud_instance/urls.py:ro
        networks:
            - fiware
        links:
            - postgres
            - keyrock

    ngsi-proxy:
        restart: on-failure
        image: fiware/ngsiproxy:latest
        hostname: ngsi-proxy
        container_name: ngsi-proxy
        environment:
            - TRUST_PROXY_HEADERS=1
        networks:
            - fiware
        expose:
            - "3000"

    pep-orion:
        restart: on-failure
        image: fiware/pep-proxy:7.0.1
        hostname: pep-orion
        container_name: pep-orion
        volumes:
            - "./pep-orion_config/config.js:/opt/fiware-pep-proxy/config.js:ro"
            - "./pep-orion_config/azf.js:/opt/fiware-pep-proxy/lib/azf.js:ro"
        networks:
            - fiware
        ports:
            - "1027:1027"
        links:
            - authzforce
        depends_on:
            keyrock:
                condition: service_healthy

    pep-idas-admin:
        restart: on-failure
        image: fiware/pep-proxy:7.0.1
        hostname: pep-idas-admin
        container_name: pep-idas-admin
        volumes:
            - "./pep-idas-admin_config/config.js:/opt/fiware-pep-proxy/config.js:ro"
            - "./pep-idas-admin_config/azf.js:/opt/fiware-pep-proxy/lib/azf.js:ro"
        networks:
            - fiware
        ports:
            - "4042:4042"
        links:
            - authzforce
        depends_on:
            keyrock:
                condition: service_healthy

    pep-idas-sensor:
        restart: on-failure
        image: fiware/pep-proxy:7.0.1
        hostname: pep-idas-sensor
        container_name: pep-idas-sensor
        volumes:
            - "./pep-idas-sensor_config/config.js:/opt/fiware-pep-proxy/config.js:ro"
            - "./pep-idas-sensor_config/azf.js:/opt/fiware-pep-proxy/lib/azf.js:ro"
        networks:
            - fiware
        ports:
            - "7897:7897"
        links:
            - authzforce
        depends_on:
            keyrock:
                condition: service_healthy

    pep-comet:
        restart: on-failure
        image: fiware/pep-proxy:7.0.1
        hostname: pep-comet
        container_name: pep-comet
        volumes:
            - "./pep-comet_config/config.js:/opt/fiware-pep-proxy/config.js:ro"
            - "./pep-comet_config/azf.js:/opt/fiware-pep-proxy/lib/azf.js:ro"
        networks:
            - fiware
        ports:
            - "8667:8667"
        links:
            - authzforce
        depends_on:
            keyrock:
                condition: service_healthy

volumes:
    letsencrypt_www: ~
    postgres_vol: ~
    mysql_vol: ~
    authzforce_vol: ~

networks:
    fiware:
        driver: bridge
        ipam:
            config:
                - subnet: 172.18.1.0/24
                  gateway: 172.18.1.1