apiVersion: apps/v1
kind: Deployment
metadata:
  name: cygnus
spec:
  selector:
    matchLabels:
      run: cygnus
  replicas: {{ .Values.cygnus.replicas }}
  template:
    metadata:
      labels:
        run: cygnus
    spec:
      containers:
      - image: {{.Values.cygnus.image}}
        name: cygnus
        ports:
        - containerPort: 8081
        - containerPort: {{ .Values.cygnus.http_source_port}}
          name: "http-source"
        volumeMounts:
        - mountPath: /opt/apache-flume/conf/agent.conf
          name: cygnus-config
          subPath: agent.conf
      restartPolicy: Always
      volumes:
      - name: cygnus-config
        configMap:
          name: cygnus-config
