apiVersion: v1
kind: Service
metadata:
  name: cygnus
  labels:
    run: cygnus
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  - name: "http-source"
    port: {{ .Values.cygnus.http_source_port}}
    targetPort: {{ .Values.cygnus.http_source_port}}
  selector:
    run: cygnus
