apiVersion: v1
kind: Service
metadata:
  name: comet
  labels:
    run: comet
spec:
  ports:
  - name: "comet"
    port: {{ .Values.comet.port }}
    targetPort: {{ .Values.comet.port }}
  selector:
    run: comet
  type: ClusterIP
