apiVersion: apps/v1
kind: Deployment
metadata:
  name: comet
spec:
  selector:
    matchLabels:
      run: comet
  replicas: {{ .Values.comet.replicas }}
  template:
    metadata:
      labels:
        run: comet
    spec:
      containers:
      - image: {{.Values.comet.image}}
        name: comet
        env:
        - name: MAX_PAGE_SIZE
          value: {{.Values.comet.max_page_size | quote}}
        ports:
        - containerPort: {{ .Values.comet.port }}
        volumeMounts:
        - mountPath: /opt/sth/config.js
          name: comet-config
          subPath: config.js
      restartPolicy: Always
      volumes:
      - name: comet-config
        configMap:
          name: comet-config
