apiVersion: v1
kind: Service
metadata:
  name: memcached
  namespace: {{.Values.fiware.namespace}}
  labels:
    run: memcached
spec:
  ports:
  - port: 11211
    name: memcached
  selector:
     run: memcached
  type: ClusterIP
