apiVersion: v1
kind: ConfigMap
metadata:
  name: hadoop-config
data:
  core-site.xml: |
    <configuration>
        <property>
            <name>fs.defaultFS</name>
            <value>hdfs://hadoop-namenode-0.namenode.{{ .Release.Namespace }}.svc.cluster.local:9000</value>
        </property>
        <property>
            <name>io.file.buffer.size</name>
            <value>131072</value>
        </property>
    </configuration>
  hdfs-site.xml: |
    <configuration>
        <property>
            <name>dfs.name.dir</name>
            <value>file:///hdfs/volume1/name</value>
            <final>true</final>
        </property>
        <property>
            <name>dfs.data.dir</name>
            <value>file:///hdfs/volume1/data</value>
            <final>true</final>
        </property>
        <property>
            <name>dfs.namenode.datanode.registration.ip-hostname-check</name>
            <value>false</value>
        </property>
        <property>
        </property>
        <property>
            <name>dfs.replication</name>
            <value>2</value>
        </property>
        <property>
            <name>dfs.webhdfs.enabled</name>
            <value>true</value>
        </property>
    </configuration>
  mapred-site.xml: |
    <configuration>
        <property>
            <name>mapreduce.job.tracker.address</name>
            <value>hadoop-yarn-0.yarn.{{ .Release.Namespace }}.svc.cluster.local</value>
        </property>
        <property>
            <name>mapreduce.framework.name</name>
            <value>yarn</value>
        </property>
        <property>
            <name>yarn.app.mapreduce.am.env</name>
            <value>HADOOP_MAPRED_HOME=${HADOOP_HOME}</value>
        </property>
        <property>
            <name>mapreduce.map.env</name>
            <value>HADOOP_MAPRED_HOME=${HADOOP_HOME}</value>
        </property>
        <property>
            <name>mapreduce.reduce.env</name>
            <value>HADOOP_MAPRED_HOME=${HADOOP_HOME}</value>
        </property>
        <property>
            <name>mapreduce.jobhistory.address</name>
            <value>hadoop-yarn-0.yarn.{{ .Release.Namespace }}.svc.cluster.local:10020</value>
        </property>
        <property>
            <name>mapreduce.jobhistory.webapp.address</name>
            <value>hadoop-yarn-0.yarn.{{ .Release.Namespace }}.svc.cluster.local:19888</value>
        </property>
        <property>
            <name>yarn.app.mapreduce.am.resource.mb</name>
            <value>1024</value>
        </property>
        <property>
            <name>mapreduce.map.memory.mb</name>
            <value>1024</value>
        </property>
        <property>
            <name>mapreduce.reduce.memory.mb</name>
            <value>1024</value>
        </property>
    </configuration>
  yarn-site.xml: |
    <configuration>
        <property>
            <name>yarn.resourcemanager.hostname</name>
            <value>hadoop-yarn-0.yarn.{{ .Release.Namespace }}.svc.cluster.local</value>
            <description>The hostname of the Resource Manager </description>
        </property>
        <property>
            <name>yarn.nodemanager.aux-services</name>
            <value>mapreduce_shuffle</value>
        </property>
        <property>
            <name>yarn.resourcemanager.scheduler.address</name>
            <value>hadoop-yarn-0.yarn.{{ .Release.Namespace }}.svc.cluster.local:8030</value>
        </property>
        <property>
            <name>yarn.resourcemanager.resource-tracker.address</name>
            <value>hadoop-yarn-0.yarn.{{ .Release.Namespace }}.svc.cluster.local:8031</value>
        </property>
        <property>
            <name>yarn.resourcemanager.address</name>
            <value>hadoop-yarn-0.yarn.{{ .Release.Namespace }}.svc.cluster.local:8032</value>
        </property>
        <property>
            <name>yarn.resourcemanager.admin.address</name>
            <value>hadoop-yarn-0.yarn.{{ .Release.Namespace }}.svc.cluster.local:8033</value>
        </property>
        <property>
            <name>yarn.resourcemanager.webapp.address</name>
            <value>hadoop-yarn-0.yarn.{{ .Release.Namespace }}.svc.cluster.local:8088</value>
        </property>
        <property>
            <name>yarn.nodemanager.resource.memory-mb</name>
            <value>4096</value>
        </property>
        <property>
            <name>yarn.scheduler.maximum-allocation-mb</name>
            <value>4096</value>
        </property>
        <property>
            <name>yarn.scheduler.minimum-allocation-mb</name>
            <value>1024</value>
        </property>
        <property>
            <name>yarn.nodemanager.vmem-check-enabled</name>
            <value>false</value>
        </property>
        <property>
            <name>yarn.resourcemanager.recovery.enabled</name>
            <value>true</value>
        </property>
        <property>
            <name>yarn.resourcemanager.store.class</name>
            <value>org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore</value>
        </property>
        <property>
            <name>yarn.resourcemanager.fs.state-store.uri</name>
            <value>file:///hdfs/volume1/yarn</value>
        </property>
    </configuration>