apiVersion: v1
kind: Service
metadata:
  name: idas-external
  labels:
    run: idas-external
spec:
  ports:
  - name: "7896"
    port: 7896
    targetPort: 7896
    nodePort: 30789
  - name: "4041"
    port: 4041
    targetPort: 4041
    nodePort: 30404
  selector:
    run: idas
  type: LoadBalancer
