apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-1
  labels:
    type: mongo
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: mongo
  hostPath:
    path: "/database/data"
