apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    name: fiware-mysql
  clusterIP: None
  selector:
     app: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql # has to match .spec.template.metadata.labels
  serviceName: "mysql"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: mysql # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mysql
        image: mysql/mysql-server:5.7.21
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "idm"
        - name: MYSQL_ROOT_HOST
          value: "%"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-pv-1
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-pv-1
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "mysql"
      resources:
        requests:
          storage: 10Gi
