apiVersion: v1
kind: Service
metadata:
  name: nginx-wirecloud
  labels:
    run: nginx-wirecloud
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    run: nginx-wirecloud
  type: LoadBalancer
