apiVersion: v1
kind: Service
metadata:
  name: ngsi-proxy-external
  labels:
    run: ngsi-proxy-external
spec:
  ports:
  - port: 30003
    targetPort: 30003
    nodePort: 30003
  selector:
    run: ngsi-proxy
  type: LoadBalancer