apiVersion: v1
kind: Service
metadata:
  name: pep-orion-external
  labels:
    run: pep-orion-external
spec:
  ports:
  - port: 1026
    targetPort: 1026
  selector:
    run: pep-orion
  type: LoadBalancer