apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-wirecloud-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/nfs/wirecloud
    server: 10.1.101.180
    readOnly: false