apiVersion: apps/v1
kind: Deployment
metadata:
  name: wirecloud
spec:
  selector:
    matchLabels:
      run: wirecloud
  replicas: 1
  template:
    metadata:
      labels:
        run: wirecloud
    spec:
      containers:
      - name: wirecloud
        image: fhjima/docker-wirecloud:latest
        ports:
        - containerPort: 80
        volumeMounts:
         - mountPath: /opt/wirecloud_instance/wirecloud_instance
           name: wirecloud-volume
        lifecycle:
         postStart:
           exec:
            command: ["/bin/sh", "-c", "chown -R wirecloud:wirecloud wirecloud_instance"]
      securityContext:
        fsGroup: 65534
      volumes:
      - name: wirecloud-volume
        persistentVolumeClaim:
          claimName: nfs-wirecloud-pvc
