# HadoopVersion
hadoopVersion: 3.1.2
# Yarn
yarn:
  # ResourceManager
  - name: yarn
    image: stfnltnr/hadoop-yarn
    size: 10Gi
    servicePorts:
#      8088 : "yarn-rm"
#      19888 : "yarn-hs"
      - port: 8088
        name: yarn-rm
      - port: 19888
        name: yarn-hs
    externalPorts:
      - port: 8088
        targetPort: 8088
        nodePort: 31808    
        name: yarn-rm
      - port: 19888
        targetPort: 19888
        nodePort: 31198    
        name: yarn-hs
      - port: 4040
        targetPort: 4040
        nodePort: 31404    
        name: spark-ui
      - port: 18080
        targetPort: 18080
        nodePort: 31180
        name: spark-hs
    containerPorts:
      - containerPort: 8088
        name: yarn-rm
      - containerPort: 19888
        name: yarn-hs
      - containerPort: 4040
        name: spark-ui
  # Namenode
  - name: namenode
    image: "stfnltnr/hadoop-namenode"
    size: 10Gi
    servicePorts:
#      9870 : "webhdfs"
#      9000 : "defaultfs"
      - port: 9870
        name: webhdfs
      - port: 9000
        name: defaultfs
    externalPorts:
      - port: 9870
        targetPort: 9870
        nodePort: 31987
    containertPorts:
      - containerPort: 9870
        name: webhdfs
      - containerPort: 9000
        name: defaultfs
# Datanode
datanode:
  name: datanode
  image: stfnltnr/hadoop-datanode
  path: /opt/hadoop-cluster/hdfs/data
  size: 50Gi
  hosts:
    - name: "i101v181"
      dnPort: 31001
      nmPort: 31011
    - name: "i101v182"
      dnPort: 31002
      nmPort: 31012
    - name: "i101v183"
      dnPort: 31033
      nmPort: 31013
# Storage
storage:
  nfs:
    path: /var/nfs/hadoop-cluster # /
    server: 10.1.101.180
    readOnly: false