# Images for the used components YARN, NameNode, DataNode
images:
  yarn: bxjulia/hadoop-yarn #stfnltnr/hadoop-yarn
  namenode: bxjulia/hadoop-namenode # stfnltnr/hadoop-namenode
  datanode: bxjulia/hadoop-datanode # stfnltnr/hadoop-datanode
  tag: latest #3.1.2
  pullPolicy: IfNotPresent

# HadoopVersion
hadoopVersion: 3.1.2

# Yarn
yarn:
  name: yarn
  size: 2Gi

# Namenode
nn:
  name: hadoop
  size: 2Gi

# Datanodes
dn:
  name: datanode
  replicas: 2
  path: /opt/hadoop/hdfs/data
  size: 4Gi
  hosts:
    - kubernetes02
    - kubernetes03

# Storage
storage:
  nfs:
    path: /var/nfs/ # + .name
    server: 10.0.0.100
    readOnly: false